---

- name: create rserve user/group
  user: name={{ rserve.user }}

- name: install epel-release for R
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: install R for CentOS 7
  yum: 
     name=R state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: download Rserve package
  get_url: url={{ rserve.source }} dest=/home/{{ ansible_ssh_user }}/
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: install Rserve package
  sudo: yes
  sudo_user: root
  shell:
    R CMD INSTALL {{ rserve.targz }}

- name: install Rserve.conf template
  sudo: yes
  sudo_user: root
  template: src={{ rserve.conf }} dest=/etc/ owner=root group=root mode=0644

- name: install Rserve.pwd template
  sudo: yes
  sudo_user: root
  template: src={{ rserve.pwdfile }} dest=/etc/ owner=root group=root mode=0644

- name: install Rserve systemd template
  sudo: yes
  sudo_user: root
  template: src={{ rserve.systemd }} dest=/usr/lib/systemd/system/ owner=root group=root mode=0644

- name: reload systemd
  sudo: yes
  sudo_user: root
  shell: systemctl daemon-reload

- name: enable Rserve
  sudo: yes
  sudo_user: root
  service: name=r.service enabled=yes

- name: start Rserve
  sudo: yes
  sudo_user: root
  service: name=r.service state=restarted
