# sets the docker http proxy setting
#  to be keyed by the setting of proxy_env.use_proxy as used by the http-proxy-conf template, for machines in inventory with
# is_behind_proxy=true

- name: set docker proxy docker.service.d directory
  sudo: yes
  file: path=/etc/systemd/system/docker.service.d state=directory
  when: is_behind_proxy == "true"


- name: add docker proxy
  sudo: yes
  template: src=http-proxy.conf.j2 dest=/etc/system/docker.service.d owner=root group=root mode=0644
  when: is_behind_proxy == "true"