#!/usr/bin/env bash

docker build -t diceunc/config_anon_files .
docker build -t diceunc/config_apps .
docker build -t diceunc/config_iplant_data_apps .
docker build -t diceunc/config_clockwork .
docker build -t diceunc/config_clm .
docker build -t diceunc/config_data_info .
docker build -t diceunc/config_dewey .
docker build -t diceunc/config_de_ui .
docker build -t diceunc/config_iplant_data_de_ui .
docker build -t diceunc/config_de_ui_nginx .
docker build -t diceunc/config_iplant_data_de_ui_nginx .
docker build -t diceunc/config_exim_sender .
docker build -t diceunc/config_info_typer .
docker build -t diceunc/config_infosquito .
docker build -t diceunc/config_iplant_email .
docker build -t diceunc/config_iplant_groups .
docker build -t diceunc/config_jex_events .
docker build -t diceunc/config_kifshare .
docker build -t diceunc/config_metadata .
docker build -t diceunc/config_monkey .
docker build -t diceunc/config_notification_agent .
docker build -t diceunc/config_saved_searches .
docker build -t diceunc/config_terrain .
docker build -t diceunc/config_iplant_data_terrain .
docker build -t diceunc/config_tree_urls .
docker build -t diceunc/config_user_preferences .
docker build -t diceunc/config_user_sessions .
